#!/usr/bin/env bash
# script that transfers a file from our client to a server.
if ['$#' -lt 4]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2:~/"

if [ #? -eq 0 ]; then
	echo "FILE WAS TRANSFERED SUCCEDDFULLY."
else
	echo "FILE TRANSFER FAILED."
fi
