#!/usr/bin/env bash
# Write a Bash script that displays Best School 10 times,
# but for the 9th iteration, displays Best School and then Hi on a new line.
n=0
text="Best School"
while [ $n -le 10 ]; do
	if [ $n -eq 9 ]; then
		echo "$text"
		echo "Hi"
	else
		echo "$text"
	fi
	((n=n+1))
done
