#!/bin/bash

# Change nginx user to nginx in nginx.conf
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf

# Change listen directive to all active IPs on port 8080
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
sed -i 's/listen [::]:80 default_server;/listen [::]:8080 default_server;/g' /etc/nginx/sites-available/default

# Restart nginx service
service nginx restart

